enemy_color: "red"
# enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/0526.xml
device: CPU
min_confidence: 0.8
use_traditional: false

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 1280
image_height: 720
fov_h: 57.7 #87.7
fov_v: 56.7 
new_fov_h: 27 #67
new_fov_v: 40.9
usb_frame_rate: 30
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "hikrobot"
exposure_ms: 5
gain: 16.9
vid_pid: "2bdf:0001"
need_rotation: true

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 125
outpost_max_temp_lost_count: 175

#####-----aimer参数-----#####
yaw_offset: 0 # degree 1.2  +是左
pitch_offset: 0  # degree 1.5 -是下 +是上
comming_angle: 40           # 目标进入角 (单位: 度) —— 识别到装甲板从侧面转入正面的判定阈值
leaving_angle: 20           # 目标离开角 (单位: 度) —— 识别到装甲板从正面转到侧向背面的消失判定阈值
left_yaw_offset: 0 #-1        # 左侧偏航角补偿 —— 修正云台向左转动时的机械安装误差或相机轴心偏差
right_yaw_offset: 0 #-0.6     # 右侧偏航角补偿 —— 修正云台向右转动时的机械安装误差
decision_speed: 10          # 决策临界角速度 (单位: rad/s) —— 区分目标是“高速运动”还是“低速运动”的阈值
high_speed_delay_time: 0.026 # 高速预瞄补偿时间 (单位: s) —— 目标高速移动时，补偿系统延迟（电控发弹+子弹飞行）所需的提前量
low_speed_delay_time: 0.010  # 低速预瞄补偿时间 (单位: s) —— 目标低速或静止时，为了防止瞄准抖动而设置的较小补偿量

defult_bullet_speed: 22

#####-----shooter参数-----#####
first_tolerance: 5 # 近距离射击容差，degree
second_tolerance: 10 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.0956px
camera_matrix: [2365.9272666695233, 0, 721.78639512153461, 0, 2366.392640571858, 501.4930920988395, 0, 0, 1]
distort_coeffs: [-0.055368902255107322, 0.13463495122612734, -0.0011088654748240042, 0.00074695691342966774, 0]

# # 相机同理想情况的偏角: yaw-1.15 pitch-0.72 roll-1.59 degree
# R_camera2gimbal: [0, 0, 1, -1, 0, 0, 0, -1, 0]
# t_camera2gimbal: [0.1301, 0, 0.04]
# # 相机同理想情况的偏角: yaw-2.35 pitch0.32 roll0.13 degree
# R_camera2gimbal: [0.041054773200914108, 0.0055373766104803834, 0.99914155306327601, -0.99915433904899031, 0.0024904523300233183, 0.041041496156538029, -0.0022610521879731209, -0.99998156738385213, 0.0056349388228866815]
# t_camera2gimbal: [0.13013863426946976, 0.0091433571355038525, 0.038450111313587755]
# 相机同理想情况的偏角: yaw-3.15 pitch0.19 roll-0.71 degree
R_camera2gimbal: [0.054934457010981763, 0.0040039733919393439, 0.99848193455364287, -0.99841289851022119, -0.01220361057480579, 0.05497959600940313, 0.01240522153479252, -0.99991751664125528, 0.0033272199593035179]
t_camera2gimbal: [0.14615249126057203, 0.010787987385981851, 0.052816373468097672]

#####-----planner-----#####
fire_thresh: 0.5

max_yaw_acc: 28000
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 28000
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"

#####-----云台扫描参数-----#####
max_scan_pitch_bottom_: -15.0   # pitch下边界（度），根据机械限位设定，安全值：-15°
max_scan_pitch_top_: 20.0       # pitch上边界（度），安全值：15°
scan_yaw_vel_: 0.03             # yaw旋转速度（度/秒），慢速：30°/s，避免过冲
scan_base_pitch_vel_: 0.01       # pitch基础速度（度/秒），保证最低运动速度
scan_ex_vel_: 0.002              # pitch额外速度（度/秒），边界处最大速度= base+ex = 15°/s
