# enemy_color: "red"
enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/0526.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 1280
image_height: 720
fov_h: 57.7 #87.7
fov_v: 56.7 
new_fov_h: 27 #67
new_fov_v: 40.9
usb_frame_rate: 120
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "hikrobot"
exposure_ms: 5
gain: 16.9
vid_pid: "2bdf:0001"
need_rotation: true

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 25
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 4 # degree -2.5  +是左
pitch_offset: 0  # degree -1 -是下 +是上
comming_angle: 40           # 目标进入角 (单位: 度) —— 识别到装甲板从侧面转入正面的判定阈值
leaving_angle: 20           # 目标离开角 (单位: 度) —— 识别到装甲板从正面转到侧向背面的消失判定阈值
left_yaw_offset: -1        # 左侧偏航角补偿 —— 修正云台向左转动时的机械安装误差或相机轴心偏差
right_yaw_offset: -0.6     # 右侧偏航角补偿 —— 修正云台向右转动时的机械安装误差
decision_speed: 10          # 决策临界角速度 (单位: rad/s) —— 区分目标是“高速运动”还是“低速运动”的阈值
high_speed_delay_time: 0.026 # 高速预瞄补偿时间 (单位: s) —— 目标高速移动时，补偿系统延迟（电控发弹+子弹飞行）所需的提前量
low_speed_delay_time: 0.010  # 低速预瞄补偿时间 (单位: s) —— 目标低速或静止时，为了防止瞄准抖动而设置的较小补偿量

defult_bullet_speed: 22

#####-----shooter参数-----#####
first_tolerance: 5 # 近距离射击容差，degree
second_tolerance: 10 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]

# 重投影误差: 0.0641px
camera_matrix: [2351.8100650138917, 0, 718.04557703289868, 0, 2352.8060260308735, 505.30273800821811, 0, 0, 1]
distort_coeffs: [-0.055410990125827835, 0.14425069668412938, -0.001281840841512254, 0.00063318149456243974, 0]

# 相机同理想情况的偏角: yaw-1.15 pitch-0.72 roll-1.59 degree
R_camera2gimbal: [0.020484728716932743, -0.012045368382986248, 0.9997176026208161, -0.99940738955079489, -0.027913573979557293, 0.020142048032752099, 0.027663072870879588, -0.99953776391300297, -0.01261003216230927]
t_camera2gimbal: [0.17097241513616423, 0.046415792745916072, -0.0007226747165814891]

#####-----planner-----#####
fire_thresh: 0.5

max_yaw_acc: 28000
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 28000
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"

#####-----云台扫描参数-----#####
max_scan_pitch_bottom_: -15.0   # pitch下边界（度），根据机械限位设定，安全值：-15°
max_scan_pitch_top_: 20.0       # pitch上边界（度），安全值：15°
scan_yaw_vel_: 0.03             # yaw旋转速度（度/秒），慢速：30°/s，避免过冲
scan_base_pitch_vel_: 0.01       # pitch基础速度（度/秒），保证最低运动速度
scan_ex_vel_: 0.002              # pitch额外速度（度/秒），边界处最大速度= base+ex = 15°/s
